medicationapp/mysite/drugs/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('list/', views.list, name='list' ),
    path('search/', views.search, name='search'),
]

medicationapp/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
import drugs

urlpatterns = [
    path('drugs/', include('drugs.urls')),
    path('admin/', admin.site.urls),
    # http://localhost:8000/list
]

medicationapp/mysite/drugs/models.py
from django.db import models


class Medication(models.Model):
    medication_name = models.CharField(max_length=200)
    manufacturer = models.CharField(max_length=200)
    date_on_market = models.DateField(blank=True, null=True)
    status = models.IntegerField(null = True, blank = True)

    def __str__(self):
        return self.medication_name

class SideEffect(models.Model):
    medication = models.ForeignKey(Medication, on_delete=models.CASCADE, null=True, blank = True)
    side_effect = models.CharField(max_length=200)
    date_published = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.side_effect

medicationapp/mysite/drugs/views.py
from django.http import HttpResponse
from .models import Medication, SideEffect
from django.shortcuts import render
from django.db.models import Q


def list(request):
   print('inside list function')
   medication_list = Medication.objects.all()
   side_effect_list = SideEffect.objects.all()
   return render(request, 'drugs/list.html', {'medication_list':medication_list,
                                               'side_effect_list':side_effect_list})



def search(request):
    # check if query is get request
    if 'query' in request.GET:
        # extract search term from request
        query = request.GET['query']

        # empty list for all results
        search_results_list = []

        # filtering medication names
        result = Medication.objects.filter(Q(medication_name__icontains=query))
        # adding medication name results to search_results_list
        for m in result:
            # adding all medications which related to side effect which is found to search_results_list
            search_results_list.append(m)

        # filtering side effects
        result2 = SideEffect.objects.filter(Q(side_effect__icontains=query))
        # loop through each side effect in result2
        for se in result2:
            # adding all medications which related to side effect which is found to search_results_list
            search_results_list.append(se.medication)
        # rendering to the list.html page

        print('results %s' % search_results_list)
        return render(request, 'drugs/list.html', {'search_results_list': search_results_list})
     # if not render to search.html page

    else:
        print('rendering search.html')
        return render(request, 'drugs/search.html')

        # IF THIS IS A GET:
        # render search.html

        # IF THIS IS A POST:
        # https://docs.djangoproject.com/en/3.0/intro/tutorial04/

        # extract search term from POST request (ex: https://stackoverflow.com/questions/39842386/django-simple-search-form)

        # search_results_list = []

        # 1 search:
        # res = Medication.objects.filter(medication_name=medication.medication_name)
        # add results to search_results_list

        # 2 search:
        # res2 = SideEffect.objects.filter()

        # find all medications for the side effects that you found
        # for se in res2:
        # search_results_list.append(se.medication)

        # return render (... search_results_list ...

    # if it is a GET render search.html
    #return render(request, 'drugs/list.html', {'medication_list':medication_list,
    #                                          'side_effect_list':side_effect_list})

medicationapp/mysite/drugs/templates/drugs/list.html
<div>
    <h1><a href="/">List Of Medications</a></h1>
</div>
{####### take each medication in the list #######}

{% for med in search_results_list %}
    <div>
        <p> {####### print medication name #######}
            {{ med.medication_name }}
            (

                {####### check if THIS med has any side effects #######}
                {% if med.sideeffect_set.all.count > 0 %}

                    {####### take each side effect from side effect list #######}
                    {% for side_effect in med.sideeffect_set.all %}

                        {####### print side effect  #######}
                        {{ side_effect.side_effect }}

                        {####### check if we need to print comma  #######}
                        {% if not forloop.last %}
                        ,
                        {% endif %}

                {% endfor %}

                {% else %}
                    No side effects
                {% endif %}
            )
        </p>
    </div>
{% endfor %}

medicationapp/mysite/drugs/templates/drugs/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>


</head>
<body>
{####### search form  #######}
<h1>Side FX</h1>
<form method="GET" action="{% url 'search' %}" >
    <input name="query"  placeholder="search">
    <input type="submit" >
    <p>Search by Medication name or Side effect</p>
</form>
</body>
</html>